"""Add status column to Post table

Revision ID: 428c23a88306
Revises: 3eca84dce27f
Create Date: 2024-02-25 19:54:23.630291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428c23a88306'
down_revision = '3eca84dce27f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'status')
    # ### end Alembic commands ###
