"""create comment table

Revision ID: 435ec8da5512
Revises: 428c23a88306
Create Date: 2024-03-08 15:01:26.624210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435ec8da5512'
down_revision = '428c23a88306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
